### ISSUE TITLE
Cannot read property 'bindings' of null

### ISSUE THREAD

**Issue by KaelThasWang0919** [mobxjs/mobx-react#532]
error: bundling failed: TypeError: Cannot read property 'bindings' of null
    at Scope.moveBindingTo (/Users/kaelthas/Desktop/ReactNativeRest/Mobx56/node_modules/@babel/traverse/lib/scope/index.js:978:12)
    at BlockScoping.updateScopeInfo (/Users/kaelthas/Desktop/ReactNativeRest/Mobx56/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:364:17)
    at BlockScoping.run (/Users/kaelthas/Desktop/ReactNativeRest/Mobx56/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:330:12)
    at PluginPass.BlockStatementSwitchStatementProgram (/Users/kaelthas/Desktop/ReactNativeRest/Mobx56/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:70:24)
    at newFn (/Users/kaelthas/Desktop/ReactNativeRest/Mobx56/node_modules/@babel/traverse/lib/visitors.js:237:21)
    at NodePath._call (/Users/kaelthas/Desktop/ReactNativeRest/Mobx56/node_modules/@babel/traverse/lib/path/context.js:65:20)
    at NodePath.call (/Users/kaelthas/Desktop/ReactNativeRest/Mobx56/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/kaelthas/Desktop/ReactNativeRest/Mobx56/node_modules/@babel/traverse/lib/path/context.js:100:12)
    at TraversalContext.visitQueue (/Users/kaelthas/Desktop/ReactNativeRest/Mobx56/node_modules/@babel/traverse/lib/context.js:142:16)

### .babel

```
{
  "presets": ["react-native"],
  "plugins": ["transform-decorators-legacy"]
}
```

### package.json

```
"dependencies": {
    "react": "16.4.1",
    "react-native": "0.56.0",
    "mobx": "^4.1.0",
    "mobx-react": "^5.0.0"
  },
  "devDependencies": {
    "babel-jest": "23.4.2",
    "babel-plugin-transform-decorators-legacy": "^1.3.5",
    "babel-preset-react-native": "4.0.0",
    "babel-preset-react-native-stage-0": "^1.0.1",
    "jest": "23.5.0",
    "react-test-renderer": "16.4.1"
  },
```

**Comment by mweststrate** [comment]
This error happens at compile time so rather should be filed at the babel or react native repositories? MobX has no influence on what happens compile time. Looks quite similar to for example https://github.com/babel/babel/issues/7627

**Comment by mweststrate** [comment]
Closing for lack of reproduction and should probably be submitted to babel as this is a babel and not a MobX error
