### ISSUE TITLE
Windows: refusing to install mobx-react as a dependency of itself

### ISSUE THREAD

**Issue by hipertracker** [mobxjs/mobx-react#54]
I can't install mobx-react on Windows 7 Enterprise SP1. I can install it on OS X but not on Windows.
```
>npm install mobx-react --save
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "mobx-react" "--save" npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code ENOSELF

npm ERR! Refusing to install mobx-react as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\hipertracker\IdeaProjects\mobx-react\npm-debug.log
```

npm-debug.log:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'mobx-react',
1 verbose cli   '--save' ]
2 info using npm@3.8.6
3 info using node@v6.1.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData mobx-react
8 silly fetchNamedPackageData mobx-react
9 silly mapToRegistry name mobx-react
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry http://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'mobx-react',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   name: 'mobx-react',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri http://registry.npmjs.org/mobx-react
14 verbose request uri http://registry.npmjs.org/mobx-react
15 verbose request no auth needed
16 info attempt registry request try #1 at 3:56:28 PM
17 verbose request id 682d08b0672ae9fc
18 verbose etag "4Y5349DQ1M6XWB3P1ZMCABHTT"
19 http request GET http://registry.npmjs.org/mobx-react
20 info retry will retry, error on last attempt: Error: unexpected end of file
21 info attempt registry request try #2 at 3:56:38 PM
22 verbose etag "4Y5349DQ1M6XWB3P1ZMCABHTT"
23 http request GET http://registry.npmjs.org/mobx-react
24 http 304 http://registry.npmjs.org/mobx-react
25 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
25 verbose headers   etag: '"4Y5349DQ1M6XWB3P1ZMCABHTT"',
25 verbose headers   'content-type': 'application/json',
25 verbose headers   'cache-control': 'max-age=300',
25 verbose headers   'accept-ranges': 'bytes',
25 verbose headers   date: 'Fri, 13 May 2016 14:56:38 GMT',
25 verbose headers   via: '1.1 varnish',
25 verbose headers   'x-served-by': 'cache-jfk1036-JFK',
25 verbose headers   'x-cache': 'MISS',
25 verbose headers   'x-cache-hits': '0',
25 verbose headers   'x-timer': 'S1463151398.759860,VS0,VE33',
25 verbose headers   vary: 'Accept-Encoding',
25 verbose headers   connection: 'Keep-Alive',
25 verbose headers   age: '0' }
26 silly get cb [ 304,
26 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
26 silly get     etag: '"4Y5349DQ1M6XWB3P1ZMCABHTT"',
26 silly get     'content-type': 'application/json',
26 silly get     'cache-control': 'max-age=300',
26 silly get     'accept-ranges': 'bytes',
26 silly get     date: 'Fri, 13 May 2016 14:56:38 GMT',
26 silly get     via: '1.1 varnish',
26 silly get     'x-served-by': 'cache-jfk1036-JFK',
26 silly get     'x-cache': 'MISS',
26 silly get     'x-cache-hits': '0',
26 silly get     'x-timer': 'S1463151398.759860,VS0,VE33',
26 silly get     vary: 'Accept-Encoding',
26 silly get     connection: 'Keep-Alive',
26 silly get     age: '0' } ]
27 verbose etag http://registry.npmjs.org/mobx-react from cache
28 verbose get saving mobx-react to C:\Users\zk4lo9p\AppData\Roaming\npm-cache\registry.npmjs.org\mobx-react\.cache.json
29 verbose correctMkdir C:\Users\zk4lo9p\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
30 silly install normalizeTree
31 silly loadCurrentTree Finishing
32 silly loadIdealTree Starting
33 silly install loadIdealTree
34 silly cloneCurrentTree Starting
35 silly install cloneCurrentTreeToIdealTree
36 silly cloneCurrentTree Finishing
37 silly loadShrinkwrap Starting
38 silly install loadShrinkwrap
39 silly loadShrinkwrap Finishing
40 silly loadAllDepsIntoIdealTree Starting
41 silly install loadAllDepsIntoIdealTree
42 silly rollbackFailedOptional Starting
43 silly rollbackFailedOptional Finishing
44 silly runTopLevelLifecycles Starting
45 silly runTopLevelLifecycles Finishing
46 silly install printInstalled
47 verbose stack Error: Refusing to install mobx-react as a dependency of itself
47 verbose stack     at checkSelf (C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:53:14)
47 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
47 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
47 verbose stack     at chain (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
47 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:16:5
47 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
47 verbose stack     at Array.forEach (native)
47 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
47 verbose stack     at Array.forEach (native)
47 verbose stack     at asyncMap (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
48 verbose cwd C:\Users\zk4lo9p\IdeaProjects\mobx-react
49 error Windows_NT 6.1.7601
50 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "mobx-react" "--save"
51 error node v6.1.0
52 error npm  v3.8.6
53 error code ENOSELF
54 error Refusing to install mobx-react as a dependency of itself
55 error If you need help, you may report this error at:
55 error     <https://github.com/npm/npm/issues>
56 verbose exit [ 1, true ]
```

**Comment by mweststrate** [comment]
for completeness sake, could you share your `dev-`, `peer-` and `dependencies` section of your own package.json?

**Comment by hipertracker** [comment]
I found the source of that problem. I created a new folder and the package name as "mobx-react". It works on OS X but Windows got crazy.

**Comment by mweststrate** [comment]
wow ok 😑

**Comment by hipertracker** [comment]
Small update. OS X also get crazy when when the new package name is 'mobx-react'. I did not notice it because I used different name.
