### ISSUE TITLE
Provider gives "TypeError: e.render is not a function" on ES5 component

### ISSUE THREAD

**Issue by EmilTholin** [mobxjs/mobx-react#68]
I wrote this very simple application:

```js
var c = observable({
  value: 0
});
c.increment = function() {
  ++c.value;
};

ReactDOM.render(
  <IncrementButton counter={c} />,
  document.getElementById("app")
);
```
Using ES5 syntax, I can write the IncrementButton component in the following ways:

```js
// Version 1
var IncrementButton = observer(function(props) {
  var counter = props.counter;
  return <button onClick={counter.increment}>{counter.value}</button>;
});

// Version 2
function IncrementButton() {
  return observer({
    render: function() {
      var counter = this.props.counter;
      return <button onClick={counter.increment}>{counter.value}</button>;
    }
  })
}

```
If I move over to the newly implemented Provider, one of them works:

```js
ReactDOM.render(
  <Provider counter={c}>
    <IncrementButton />
  </Provider>,
  document.getElementById("app")
);

// Version 1: Works great!
var IncrementButton = observer(['counter'], function(props) {
  var counter = props.counter;
  return <button onClick={counter.increment}>{counter.value}</button>;
});

// Version 2: Error!
function IncrementButton() {
  return observer(['counter'], {
    render: function() {
      var counter = this.props.counter;
      return <button onClick={counter.increment}>{counter.value}</button>;
    }
  });
}
```

Version 2 gives rise to the following error:

```
"TypeError: e.render is not a function
    at _renderValidatedComponentWithoutOwnerOrContext (https://fbcdn-dragon-a.akamaihd.net/hphotos-ak-xta1/t39.3284-6/12624096_747368668729465_1053913233_n.js:13:18763)
    at _renderValidatedComponent (https://fbcdn-dragon-a.akamaihd.net/hphotos-ak-xta1/t39.3284-6/12624096_747368668729465_1053913233_n.js:13:18851)
    at mountComponent (https://fbcdn-dragon-a.akamaihd.net/hphotos-ak-xta1/t39.3284-6/12624096_747368668729465_1053913233_n.js:13:15153)
    at Object.mountComponent (https://fbcdn-dragon-a.akamaihd.net/hphotos-ak-xta1/t39.3284-6/12624096_747368668729465_1053913233_n.js:15:4834)
    at mountComponent (https://fbcdn-dragon-a.akamaihd.net/hphotos-ak-xta1/t39.3284-6/12624096_747368668729465_1053913233_n.js:13:15249)
    at Object.mountComponent (https://fbcdn-dragon-a.akamaihd.net/hphotos-ak-xta1/t39.3284-6/12624096_747368668729465_1053913233_n.js:15:4834)
    at mountComponent (https://fbcdn-dragon-a.akamaihd.net/hphotos-ak-xta1/t39.3284-6/12624096_747368668729465_1053913233_n.js:13:15249)
    at Object.mountComponent (https://fbcdn-dragon-a.akamaihd.net/hphotos-ak-xta1/t39.3284-6/12624096_747368668729465_1053913233_n.js:15:4834)
    at v (https://fbcdn-dragon-a.akamaihd.net/hphotos-ak-xta1/t39.3284-6/12624096_747368668729465_1053913233_n.js:14:22561)
    at r.perform (https://fbcdn-dragon-a.akamaihd.net/hphotos-ak-xta1/t39.3284-6/12624096_747368668729465_1053913233_n.js:16:1661)"
```

I used the following [JS Bin](http://jsbin.com/kofisurali/1/edit?js,console,output), and I get the same error trying it on my own machine. 

Am I using the Provider incorrectly, or might there be something wrong? Thanks.

**Comment by mweststrate** [comment]
Version 1 is correct, version 2 mixes `React.createClass` syntax with stateless function syntax, what you need in that case is:

```javascript
var IncrementButton = observer(['counter'], React.createClass({
    render: function() {
      var counter = this.props.counter;
      return <button onClick={counter.increment}>{counter.value}</button>;
    }
});
```

**Comment by EmilTholin** [comment]
That works great. Thank you.

I've stayed away from `createClass` since I read [Eric Elliot's blog post](https://medium.com/javascript-scene/baby-s-first-reaction-2103348eccdd#66e4) on the matter. I am just puzzled since it works without `createClass` when not using the provider in my first example. Do you think it is possible to make this use case work, or is it simply wrong on my part?

**Comment by mweststrate** [comment]
Not sure, I'm not entirely sure whether the setup he is using is idiomatic react usage in the first place. I don't think I saw it somewhere in the official docs? (I only know the ES6 class / createClass / stateless function component approaches). Adding a fourth variant to declare components might just add confusion?

**Comment by EmilTholin** [comment]
You are right. Eric uses that way of creating components quite a lot, but it is nowhere to be found in the docs, as you say. I will just start using `createClass` from here on out. No biggie! Thank you again.
